"use client"

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'pt' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Header
    'header.balance': 'Saldo:',
    'header.deposit': 'Recargar en 1 clic',
    'header.login': 'Iniciar sesión',
    'header.register': 'Registrarse',
    'header.games': 'Juegos',
    'header.casino': 'Casino',
    'header.bonuses': 'Bonificaciones',
    'header.live_games': 'Juegos en vivo',
    'header.more': 'Más',
    'header.account': 'Cuenta',
    'header.menu': 'Menú',
    
    // Profile page
    'profile.my_profile': 'Mi perfil',
    'profile.personal_data': 'Datos personales',
    'profile.security': 'Seguro',
    'profile.email_not_verified': 'Tu correo electrónico no ha sido verificado. Por favor, verifica tu correo electrónico y no olvides revisar tu carpeta de spam.',
    'profile.resend_email': 'Enviar correo nuevamente',
    'profile.first_name': 'Nombre',
    'profile.last_name': 'Apellido',
    'profile.birthday': 'Cumpleaños',
    'profile.gender': 'Sexo',
    'profile.country': 'País',
    'profile.city': 'Ciudad',
    'profile.address': 'Dirección',
    'profile.phone_number': 'Número de teléfono',
    'profile.email': 'Correo electrónico',
    'profile.male': 'Masculino',
    'profile.female': 'Femenino',
    'profile.save': 'Guardar',
    'profile.security_settings': 'Configuración de seguridad',
    'profile.old_password': 'Contraseña Antigua',
    'profile.new_password': 'Nueva Contraseña',
    'profile.confirm_password': 'Confirmar Contraseña',
    'profile.send': 'Enviar',
    'profile.profile_updated': 'Perfil actualizado exitosamente',
    
    // Deposit page
    'deposit.choose_bonus': '¡Elige tu bono!',
    'deposit.choose_amount': '¡Elige tu monto!',
    'deposit.recharge': 'Recargar',
    'deposit.bonus_percentage': 'Bono +{percentage}%',
    'deposit.amount': 'Monto de depósito',
    'deposit.enter_amount': 'Ingresa tu monto (ej: 100000)',
    'deposit.minimum_amount': 'Monto mínimo:',
    'deposit.first_name': 'Nombre de pila',
    'deposit.last_name': 'Apellido',
    'deposit.address': 'Dirección',
    'deposit.state': 'Estado/Departamento',
    'deposit.city': 'Ciudad',
    'deposit.zip': 'Código postal',
    'deposit.birth_date': 'Fecha de nacimiento',
    'deposit.phone_no': 'Número de teléfono',
    'deposit.tax_id': 'Número de identificación',
    'deposit.phone_error': 'El número de teléfono debe tener exactamente 10 dígitos',
    'deposit.pagos_success': 'Pago procesado exitosamente. Se abrirá la página de pago.',
    'deposit.pagos_error': 'Error al procesar el pago. Por favor, inténtelo de nuevo.',
    'deposit.terms_acceptance': 'Al hacer clic en Depósito, acepta los',
    'deposit.terms_conditions': 'Términos y condiciones',
    'deposit.privacy_policy': 'Política de privacidad',
    'deposit.deposit_button': 'Depositar',
    'deposit.minimum_required': '⚠️ Monto mínimo requerido',
    'deposit.minimum_message': 'El monto mínimo de depósito es 60,000 {currency}. Por favor, ingresa un monto mayor o igual a este valor.',
    'deposit.understood': 'Entendido',
    'deposit.safety_pay': 'SafetyPay Express 4.0',
    
    // Additional deposit texts
    'deposit.page_title': 'Recargar',
    'deposit.choose_method': 'Elige el método de depósito',
    
    // Detalization page
    'detalization.deposits': 'depósitos',
    'detalization.payments': 'pagos',
    'detalization.date_time': 'Fecha y Hora',
    'detalization.transaction': 'Transacción',
    'detalization.amount': 'Monto',
    'detalization.payment_method': 'Método de pago',
    'detalization.status': 'Estado',
    'detalization.empty_deposits': 'La historia de operaciones está vacía',
    'detalization.empty_payments': 'Aún no hay solicitudes para recibir ganancias',
    'detalization.deposits_description': 'Recarga tu cuenta, realiza apuestas y obtén ganancias!',
    'detalization.payments_description': 'Las solicitudes de ganancias se mostrarán aquí',
    'detalization.recharge_button': 'Recargar',
    'detalization.withdraw_button': 'Obtener una ganancia',
    'detalization.status_completed': 'completado',
    'detalization.status_approved': 'aprobado',
    'detalization.status_waiting': 'esperando',
    'detalization.status_pending': 'pendiente',
    
    // Withdrawal page
    'withdrawal.page_title': 'Retiro de fondos',
    'withdrawal.choose_method': 'Elige el método de retiro',
    'withdrawal.bank_transfer': 'TRANSFERENCIA BANCARIA',
    'withdrawal.details': 'Detalles de retiro',
    'withdrawal.ready_to_withdraw': 'Listo para retirar efectivo',
    'withdrawal.amount_label': 'Importe (Máx: {balance} {currency})',
    'withdrawal.minimum_amount': 'Mínimo 150,000 COP',
    'withdrawal.client_phone': 'Teléfono del cliente',
    'withdrawal.account_type': 'Cuenta corriente o ahorro',
    'withdrawal.account_type_placeholder': 'corriente o ahorro',
    'withdrawal.account_number': 'Número de cuenta',
    'withdrawal.document_type': 'Tipo de Documento',
    'withdrawal.document_type_placeholder': 'cedula, pasaporte, etc.',
    'withdrawal.document_number': 'Número del Documento',
    'withdrawal.bank': 'Banco',
    'withdrawal.select_bank': 'Seleccione su banco',
    'withdrawal.bancolombia': 'Bancolombia',
    'withdrawal.davivienda': 'Davivienda',
    'withdrawal.bbva': 'BBVA',
    'withdrawal.banco_bogota': 'Banco de Bogotá',
    'withdrawal.banco_agrario': 'Banco Agrario',
    'withdrawal.banco_popular': 'Banco Popular',
    'withdrawal.banco_occidente': 'Banco de Occidente',
    'withdrawal.banco_caja_social': 'Banco Caja Social',
    'withdrawal.request_withdrawal': 'Solicitar retiro',
    
    // Bonuses page
    'bonuses.hero_title': '¡El casino en línea más generoso!',
    'bonuses.all_bonuses': 'Todos los bonos',
    'bonuses.my_active_bonuses': 'Mis bonos activos',
    'bonuses.available_for_me': 'Disponible para mí',
    'bonuses.archive': 'Archivo',
    'bonuses.promo_title': '¡Hasta un +400% en tu depósito con un código promocional!',
    'bonuses.promo_description': 'Cada código promocional es único y otorga del +50% al +1000% a tu saldo de bonificación.',
    'bonuses.confirm': 'Confirmar',
    'bonuses.activation_error': 'Error de activación',
    'bonuses.promo_not_found': 'Código de promoción no encontrado.',
    'bonuses.ok': 'Ok',
    'bonuses.promo_placeholder': 'Ingresa tu código promocional',
    
    // All Games page
    'all_games.top_games': 'Top Juegos',
    'all_games.popular': 'Popular',
    'all_games.hot': 'Calientes',
    'all_games.search_placeholder': 'Buscar...',
    'all_games.providers': 'Proveedores',
    'all_games.categories': 'Categorías',
    'all_games.clear': 'Limpiar',
    'all_games.all_games': 'Todos los Juegos',
    'all_games.all_games_mobile': 'Todos los juegos',
    'all_games.game': 'juego',
    'all_games.games': 'juegos',
    
    // Verification page
    'verification.personal_data': 'Datos personales',
    'verification.first_name': 'Nombre',
    'verification.last_name': 'Apellido',
    'verification.birthday': 'Cumpleaños',
    'verification.gender': 'Sexo',
    'verification.male': 'Masculino',
    'verification.female': 'Femenino',
    'verification.country': 'País',
    'verification.city': 'Ciudad',
    'verification.address': 'Dirección',
    'verification.phone_number': 'Número de teléfono',
    'verification.email': 'Correo electrónico',
    'verification.update_data': 'Actualizar datos',
    'verification.data_updated_successfully': 'Datos actualizados exitosamente',
    'verification.error_updating_data': 'Error al actualizar los datos',
    
    // ProfileSidebar component
    'sidebar.my_profile': 'Mi perfil',
    'sidebar.recharge': 'Recargar',
    'sidebar.withdraw': 'Retirar',
    'sidebar.transaction_history': 'Historial de transacciones',
    'sidebar.bonuses': 'Bonificaciones',
    'sidebar.verification': 'Verificación',
    'sidebar.balance': 'Saldo:',
    'sidebar.user_id': 'ID de usuario:',
    'sidebar.quick_recharge': 'Recargar en 1 clic',
    
    // Loading page
    'loading.welcome_message': '¡Bienvenido al casino más emocionante!',
    'loading.loading_text': 'Cargando tu experiencia de juego...',
    
    // Game mode dialog
    'game_mode.select_mode': 'Selecciona el modo de juego',
    'game_mode.demo_mode': 'Modo Demo',
    'game_mode.demo_description': 'Juega gratis sin riesgo de dinero real',
    'game_mode.real_mode': 'Modo Real',
    'game_mode.real_description': 'Juega con dinero real y gana premios',
    'game_mode.free': 'Gratis',
    'game_mode.real_money': 'Dinero Real',
    'game_mode.cancel': 'Cancelar',
    'game_mode.please_select_mode': 'Por favor selecciona un modo de juego',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.aviator': 'Aviator',
    'nav.games': 'Juegos',
    'nav.casino': 'Casino',
    'nav.bonuses': 'Bonificaciones',
    'nav.live_games': 'Juegos <br> en vivo',
    
    // Footer
    'footer.general_terms': 'Condiciones generales',
    'footer.responsible_gaming': 'Juego responsable',
    'footer.contact': 'Contacto',
    'footer.affiliate_program': 'Programa de Afiliados',
    'footer.privacy_policy': 'Política de Privacidad',
    'footer.about_us': 'Sobre nosotros',
    'footer.account_payments': 'Cuenta, Pagos y Bonos',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    
    // Pages
    'page.deposit': 'Recargar',
    'page.withdrawal': 'Retiro de fondos',
    'page.profile': 'Mi perfil',
    'page.verification': 'Verificación',
    'page.detalization': 'Detalización',
    'page.games': 'Juegos',
    'page.casino': 'Casino',
    'page.bonuses': 'Bonificaciones',
    'page.policies': 'Políticas',
    
    // Home page
    'home.casino': 'Casino',
    'home.live_games': 'Juegos en vivo',
    'home.all_games': 'Todos los juegos',
    'home.crash': 'Crash',
    'home.valor_games': 'Valor Games',
    'home.all_games_filter': 'All Games',
    
    // Footer
    'footer.company_info': 'La información en el sitio es proporcionada por el operador del sitio - la empresa ValorBet N.V., registrada en la dirección: Palm Avenue 10, Rosebank, Sint Maarten. La actividad de la empresa ValorBet N.V. está licenciada y regulada por IslandGames N.V. (número de licencia: No. 1234/JAZ2021-567; válida hasta el 31 de diciembre de 2025) y por la legislación de Sint Maarten. Los pagos son procesados por Global Invest Solutions Ltd (número de registro: HE 654321, dirección: Ocean Drive 22, Mesa Verde, 5678, Limassol, Chipre), una subsidiaria de ValorBet N.V.',
    'footer.copyright': '© 2021 - 2025. ValorCasino. Derechos Reservados',
    'footer.legal_info': 'Información Legal',
    
    // Policies page
    'policies.user_agreement': 'Acuerdo de usuario',
    'policies.responsible_gambling': 'Juego responsable',
    'policies.responsible_gaming': 'Juego responsable',
    'policies.general_terms': 'Condiciones generales',
    'policies.risk_disclosure': 'Divulgación de riesgos',
    'policies.deposits_withdrawals': 'Reposición y retirada de fondos',
    'policies.cancellation_policy': 'Política de cancelación',
    'policies.refund_policy': 'Política de reembolso',
    'policies.privacy_policy': 'Política de privacidad',
    'policies.about_us': 'Sobre nosotros',
    'policies.contact': 'Contacto',
    'policies.fairness': 'Métodos de prueba de imparcialidad y RNG',
    'policies.account_payments': 'Cuenta, Pagos y Bonos',
    'policies.aml': 'Políticas AML',
    'policies.self_exclusion': 'Autoexclusión',
    'policies.kyc': 'Política de KYC',
    'policies.dispute_resolution': 'Resolución de Disputas',
  },
  en: {
    // Header
    'header.balance': 'Balance:',
    'header.deposit': 'Deposit in 1 click',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.games': 'Games',
    'header.casino': 'Casino',
    'header.bonuses': 'Bonuses',
    'header.live_games': 'Live Games',
    'header.more': 'More',
    'header.account': 'Account',
    'header.menu': 'Menu',
    
    // Profile page
    'profile.my_profile': 'My Profile',
    'profile.personal_data': 'Personal Data',
    'profile.security': 'Security',
    'profile.email_not_verified': 'Your email has not been verified. Please verify your email and don\'t forget to check your spam folder.',
    'profile.resend_email': 'Resend Email',
    'profile.first_name': 'First Name',
    'profile.last_name': 'Last Name',
    'profile.birthday': 'Birthday',
    'profile.gender': 'Gender',
    'profile.country': 'Country',
    'profile.city': 'City',
    'profile.address': 'Address',
    'profile.phone_number': 'Phone Number',
    'profile.email': 'Email',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.save': 'Save',
    'profile.security_settings': 'Security Settings',
    'profile.old_password': 'Old Password',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm Password',
    'profile.send': 'Send',
    'profile.profile_updated': 'Profile updated successfully',
    
    // Deposit page
    'deposit.choose_bonus': 'Choose your bonus!',
    'deposit.choose_amount': 'Choose your amount!',
    'deposit.recharge': 'Recharge',
    'deposit.bonus_percentage': 'Bonus +{percentage}%',
    'deposit.amount': 'Deposit amount',
    'deposit.enter_amount': 'Enter your amount (e.g: 100000)',
    'deposit.minimum_amount': 'Minimum amount:',
    'deposit.first_name': 'First name',
    'deposit.last_name': 'Last name',
    'deposit.address': 'Address',
    'deposit.state': 'State',
    'deposit.city': 'City',
    'deposit.zip': 'ZIP Code',
    'deposit.birth_date': 'Birth Date',
    'deposit.phone_no': 'Phone Number',
    'deposit.tax_id': 'Tax ID',
    'deposit.phone_error': 'Phone number must be exactly 10 digits',
    'deposit.pagos_success': 'Payment processed successfully. Payment page will open.',
    'deposit.pagos_error': 'Error processing payment. Please try again.',
    'deposit.terms_acceptance': 'By clicking Deposit, you accept the',
    'deposit.terms_conditions': 'Terms and conditions',
    'deposit.privacy_policy': 'Privacy policy',
    'deposit.deposit_button': 'Deposit',
    'deposit.minimum_required': '⚠️ Minimum amount required',
    'deposit.minimum_message': 'The minimum deposit amount is 60,000 {currency}. Please enter an amount greater than or equal to this value.',
    'deposit.understood': 'Understood',
    'deposit.safety_pay': 'SafetyPay Express 4.0',
    
    // Additional deposit texts
    'deposit.page_title': 'Recharge',
    'deposit.choose_method': 'Choose deposit method',
    
    // Detalization page
    'detalization.deposits': 'deposits',
    'detalization.payments': 'payments',
    'detalization.date_time': 'Date and Time',
    'detalization.transaction': 'Transaction',
    'detalization.amount': 'Amount',
    'detalization.payment_method': 'Payment Method',
    'detalization.status': 'Status',
    'detalization.empty_deposits': 'Transaction history is empty',
    'detalization.empty_payments': 'No withdrawal requests yet',
    'detalization.deposits_description': 'Recharge your account, place bets and earn profits!',
    'detalization.payments_description': 'Withdrawal requests will be shown here',
    'detalization.recharge_button': 'Recharge',
    'detalization.withdraw_button': 'Get profit',
    'detalization.status_completed': 'completed',
    'detalization.status_approved': 'approved',
    'detalization.status_waiting': 'waiting',
    'detalization.status_pending': 'pending',
    
    // Withdrawal page
    'withdrawal.page_title': 'Withdrawal',
    'withdrawal.choose_method': 'Choose withdrawal method',
    'withdrawal.bank_transfer': 'BANK TRANSFER',
    'withdrawal.details': 'Withdrawal details',
    'withdrawal.ready_to_withdraw': 'Ready to withdraw cash',
    'withdrawal.amount_label': 'Amount (Max: {balance} {currency})',
    'withdrawal.minimum_amount': 'Minimum',
    'withdrawal.client_phone': 'Client phone',
    'withdrawal.account_type': 'Current or savings account',
    'withdrawal.account_type_placeholder': 'current or savings',
    'withdrawal.account_number': 'Account number',
    'withdrawal.document_type': 'Document Type',
    'withdrawal.document_type_placeholder': 'ID, passport, etc.',
    'withdrawal.document_number': 'Document Number',
    'withdrawal.bank': 'Bank',
    'withdrawal.select_bank': 'Select your bank',
    'withdrawal.bancolombia': 'Bancolombia',
    'withdrawal.davivienda': 'Davivienda',
    'withdrawal.bbva': 'BBVA',
    'withdrawal.banco_bogota': 'Banco de Bogotá',
    'withdrawal.banco_agrario': 'Banco Agrario',
    'withdrawal.banco_popular': 'Banco Popular',
    'withdrawal.banco_occidente': 'Banco de Occidente',
    'withdrawal.banco_caja_social': 'Banco Caja Social',
    'withdrawal.request_withdrawal': 'Request withdrawal',
    
    // Bonuses page
    'bonuses.hero_title': 'The most generous online casino!',
    'bonuses.all_bonuses': 'All bonuses',
    'bonuses.my_active_bonuses': 'My active bonuses',
    'bonuses.available_for_me': 'Available for me',
    'bonuses.archive': 'Archive',
    'bonuses.promo_title': 'Up to +400% on your deposit with a promotional code!',
    'bonuses.promo_description': 'Each promotional code is unique and grants from +50% to +1000% to your bonus balance.',
    'bonuses.confirm': 'Confirm',
    'bonuses.activation_error': 'Activation error',
    'bonuses.promo_not_found': 'Promotional code not found.',
    'bonuses.ok': 'Ok',
    'bonuses.promo_placeholder': 'Enter your promotional code',
    
    // All Games page
    'all_games.top_games': 'Top Games',
    'all_games.popular': 'Popular',
    'all_games.hot': 'Hot',
    'all_games.search_placeholder': 'Search...',
    'all_games.providers': 'Providers',
    'all_games.categories': 'Categories',
    'all_games.clear': 'Clear',
    'all_games.all_games': 'All Games',
    'all_games.all_games_mobile': 'All games',
    'all_games.game': 'game',
    'all_games.games': 'games',
    
    // Verification page
    'verification.personal_data': 'Personal Data',
    'verification.first_name': 'First Name',
    'verification.last_name': 'Last Name',
    'verification.birthday': 'Birthday',
    'verification.gender': 'Gender',
    'verification.male': 'Male',
    'verification.female': 'Female',
    'verification.country': 'Country',
    'verification.city': 'City',
    'verification.address': 'Address',
    'verification.phone_number': 'Phone Number',
    'verification.email': 'Email',
    'verification.update_data': 'Update Data',
    'verification.data_updated_successfully': 'Data updated successfully',
    'verification.error_updating_data': 'Error updating data',
    
    // ProfileSidebar component
    'sidebar.my_profile': 'My Profile',
    'sidebar.recharge': 'Recharge',
    'sidebar.withdraw': 'Withdraw',
    'sidebar.transaction_history': 'Transaction History',
    'sidebar.bonuses': 'Bonuses',
    'sidebar.verification': 'Verification',
    'sidebar.balance': 'Balance:',
    'sidebar.user_id': 'User ID:',
    'sidebar.quick_recharge': 'Quick Recharge',
    
    // Loading page
    'loading.welcome_message': 'Welcome to the most exciting casino!',
    'loading.loading_text': 'Loading your gaming experience...',
    
    // Game mode dialog
    'game_mode.select_mode': 'Select Game Mode',
    'game_mode.demo_mode': 'Demo Mode',
    'game_mode.demo_description': 'Play for free without real money risk',
    'game_mode.real_mode': 'Real Mode',
    'game_mode.real_description': 'Play with real money and win prizes',
    'game_mode.free': 'Free',
    'game_mode.real_money': 'Real Money',
    'game_mode.cancel': 'Cancel',
    'game_mode.please_select_mode': 'Please select a game mode',
    
    // Navigation
    'nav.home': 'Home',
    'nav.aviator': 'Aviator',
    'nav.games': 'Games',
    'nav.casino': 'Casino',
    'nav.bonuses': 'Bonuses',
    'nav.live_games': 'Live Games',
    
    // Footer
    'footer.general_terms': 'General Terms and Conditions',
    'footer.responsible_gaming': 'Responsible Gaming',
    'footer.contact': 'Contact',
    'footer.affiliate_program': 'Affiliate Program',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.about_us': 'About Us',
    'footer.account_payments': 'Account, Payments, and Bonuses',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Pages
    'page.deposit': 'Deposit',
    'page.withdrawal': 'Withdrawal',
    'page.profile': 'My Profile',
    'page.verification': 'Verification',
    'page.detalization': 'Detalization',
    'page.games': 'Games',
    'page.casino': 'Casino',
    'page.bonuses': 'Bonuses',
    'page.policies': 'Policies',
    
    // Home page
    'home.casino': 'Casino',
    'home.live_games': 'Live Games',
    'home.all_games': 'All Games',
    'home.crash': 'Crash',
    'home.valor_games': 'Valor Games',
    'home.all_games_filter': 'All Games',
    
    // Footer
    'footer.company_info': 'The information on the site is provided by the site operator - ValorBet N.V. company, registered at: Palm Avenue 10, Rosebank, Sint Maarten. The activity of ValorBet N.V. company is licensed and regulated by IslandGames N.V. (license number: No. 1234/JAZ2021-567; valid until December 31, 2025) and by Sint Maarten legislation. Payments are processed by Global Invest Solutions Ltd (registration number: HE 654321, address: Ocean Drive 22, Mesa Verde, 5678, Limassol, Cyprus), a subsidiary of ValorBet N.V.',
    'footer.copyright': '© 2021 - 2025. ValorCasino. All Rights Reserved',
    'footer.legal_info': 'Legal Information',
    
    // Policies page
    'policies.user_agreement': 'User Agreement',
    'policies.responsible_gambling': 'Responsible Gambling',
    'policies.responsible_gaming': 'Responsible Gaming',
    'policies.general_terms': 'General Terms and Conditions',
    'policies.risk_disclosure': 'Risk Disclosure',
    'policies.deposits_withdrawals': 'Deposits and Withdrawals',
    'policies.cancellation_policy': 'Cancellation Policy',
    'policies.refund_policy': 'Refund Policy',
    'policies.privacy_policy': 'Privacy Policy',
    'policies.about_us': 'About Us',
    'policies.contact': 'Contact',
    'policies.fairness': 'Fairness Methods and RNG Proof',
    'policies.account_payments': 'Account, Payments and Bonuses',
    'policies.aml': 'AML Policies',
    'policies.self_exclusion': 'Self-Exclusion',
    'policies.kyc': 'KYC Policy',
    'policies.dispute_resolution': 'Dispute Resolution',
  },
  pt: {
    // Header
    'header.balance': 'Saldo:',
    'header.deposit': 'Depositar em 1 clique',
    'header.login': 'Entrar',
    'header.register': 'Registrar',
    'header.games': 'Jogos',
    'header.casino': 'Cassino',
    'header.bonuses': 'Bônus',
    'header.live_games': 'Jogos ao Vivo',
    'header.more': 'Mais',
    'header.account': 'Conta',
    'header.menu': 'Menu',
    
    // Profile page
    'profile.my_profile': 'Meu Perfil',
    'profile.personal_data': 'Dados Pessoais',
    'profile.security': 'Segurança',
    'profile.email_not_verified': 'Seu email não foi verificado. Por favor, verifique seu email e não esqueça de verificar sua pasta de spam.',
    'profile.resend_email': 'Reenviar Email',
    'profile.first_name': 'Nome',
    'profile.last_name': 'Sobrenome',
    'profile.birthday': 'Aniversário',
    'profile.gender': 'Sexo',
    'profile.country': 'País',
    'profile.city': 'Cidade',
    'profile.address': 'Endereço',
    'profile.phone_number': 'Número de Telefone',
    'profile.email': 'Email',
    'profile.male': 'Masculino',
    'profile.female': 'Feminino',
    'profile.save': 'Salvar',
    'profile.security_settings': 'Configurações de Segurança',
    'profile.old_password': 'Senha Antiga',
    'profile.new_password': 'Nova Senha',
    'profile.confirm_password': 'Confirmar Senha',
    'profile.send': 'Enviar',
    'profile.profile_updated': 'Perfil atualizado com sucesso',
    
    // Deposit page
    'deposit.choose_bonus': 'Escolha seu bônus!',
    'deposit.choose_amount': 'Escolha seu valor!',
    'deposit.recharge': 'Recarregar',
    'deposit.bonus_percentage': 'Bônus +{percentage}%',
    'deposit.amount': 'Valor do depósito',
    'deposit.enter_amount': 'Digite seu valor (ex: 100000)',
    'deposit.minimum_amount': 'Valor mínimo:',
    'deposit.first_name': 'Nome',
    'deposit.last_name': 'Sobrenome',
    'deposit.address': 'Endereço',
    'deposit.state': 'Estado',
    'deposit.city': 'Cidade',
    'deposit.zip': 'CEP',
    'deposit.birth_date': 'Data de Nascimento',
    'deposit.phone_no': 'Número de Telefone',
    'deposit.tax_id': 'CPF/CNPJ',
    'deposit.phone_error': 'O número de telefone deve ter exatamente 10 dígitos',
    'deposit.pagos_success': 'Pagamento processado com sucesso. A página de pagamento será aberta.',
    'deposit.pagos_error': 'Erro ao processar pagamento. Tente novamente.',
    'deposit.terms_acceptance': 'Ao clicar em Depósito, você aceita os',
    'deposit.terms_conditions': 'Termos e condições',
    'deposit.privacy_policy': 'Política de privacidade',
    'deposit.deposit_button': 'Depositar',
    'deposit.minimum_required': '⚠️ Valor mínimo necessário',
    'deposit.minimum_message': 'O valor mínimo de depósito é 60,000 {currency}. Por favor, digite um valor maior ou igual a este valor.',
    'deposit.understood': 'Entendido',
    'deposit.safety_pay': 'SafetyPay Express 4.0',
    
    // Additional deposit texts
    'deposit.page_title': 'Recarregar',
    'deposit.choose_method': 'Escolha o método de depósito',
    
    // Detalization page
    'detalization.deposits': 'depósitos',
    'detalization.payments': 'pagamentos',
    'detalization.date_time': 'Data e Hora',
    'detalization.transaction': 'Transação',
    'detalization.amount': 'Valor',
    'detalization.payment_method': 'Método de Pagamento',
    'detalization.status': 'Status',
    'detalization.empty_deposits': 'O histórico de transações está vazio',
    'detalization.empty_payments': 'Ainda não há solicitações de saque',
    'detalization.deposits_description': 'Recarregue sua conta, faça apostas e obtenha lucros!',
    'detalization.payments_description': 'As solicitações de saque serão mostradas aqui',
    'detalization.recharge_button': 'Recarregar',
    'detalization.withdraw_button': 'Obter lucro',
    'detalization.status_completed': 'concluído',
    'detalization.status_approved': 'aprovado',
    'detalization.status_waiting': 'aguardando',
    'detalization.status_pending': 'pendente',
    
    // Withdrawal page
    'withdrawal.page_title': 'Saque',
    'withdrawal.choose_method': 'Escolha o método de saque',
    'withdrawal.bank_transfer': 'TRANSFERÊNCIA BANCÁRIA',
    'withdrawal.details': 'Detalhes do saque',
    'withdrawal.ready_to_withdraw': 'Pronto para sacar dinheiro',
    'withdrawal.amount_label': 'Valor (Máx: {balance} {currency})',
    'withdrawal.minimum_amount': 'Mínimo',
    'withdrawal.client_phone': 'Telefone do cliente',
    'withdrawal.account_type': 'Conta corrente ou poupança',
    'withdrawal.account_type_placeholder': 'corrente ou poupança',
    'withdrawal.account_number': 'Número da conta',
    'withdrawal.document_type': 'Tipo de Documento',
    'withdrawal.document_type_placeholder': 'RG, passaporte, etc.',
    'withdrawal.document_number': 'Número do Documento',
    'withdrawal.bank': 'Banco',
    'withdrawal.select_bank': 'Selecione seu banco',
    'withdrawal.bancolombia': 'Bancolombia',
    'withdrawal.davivienda': 'Davivienda',
    'withdrawal.bbva': 'BBVA',
    'withdrawal.banco_bogota': 'Banco de Bogotá',
    'withdrawal.banco_agrario': 'Banco Agrario',
    'withdrawal.banco_popular': 'Banco Popular',
    'withdrawal.banco_occidente': 'Banco de Occidente',
    'withdrawal.banco_caja_social': 'Banco Caja Social',
    'withdrawal.request_withdrawal': 'Solicitar saque',
    
    // Bonuses page
    'bonuses.hero_title': 'O cassino online mais generoso!',
    'bonuses.all_bonuses': 'Todos os bônus',
    'bonuses.my_active_bonuses': 'Meus bônus ativos',
    'bonuses.available_for_me': 'Disponível para mim',
    'bonuses.archive': 'Arquivo',
    'bonuses.promo_title': 'Até +400% no seu depósito com um código promocional!',
    'bonuses.promo_description': 'Cada código promocional é único e concede de +50% a +1000% ao seu saldo de bônus.',
    'bonuses.confirm': 'Confirmar',
    'bonuses.activation_error': 'Erro de ativação',
    'bonuses.promo_not_found': 'Código promocional não encontrado.',
    'bonuses.ok': 'Ok',
    'bonuses.promo_placeholder': 'Digite seu código promocional',
    
    // All Games page
    'all_games.top_games': 'Top Jogos',
    'all_games.popular': 'Popular',
    'all_games.hot': 'Quente',
    'all_games.search_placeholder': 'Buscar...',
    'all_games.providers': 'Provedores',
    'all_games.categories': 'Categorias',
    'all_games.clear': 'Limpar',
    'all_games.all_games': 'Todos os Jogos',
    'all_games.all_games_mobile': 'Todos os jogos',
    'all_games.game': 'jogo',
    'all_games.games': 'jogos',
    
    // Verification page
    'verification.personal_data': 'Dados Pessoais',
    'verification.first_name': 'Nome',
    'verification.last_name': 'Sobrenome',
    'verification.birthday': 'Aniversário',
    'verification.gender': 'Sexo',
    'verification.male': 'Masculino',
    'verification.female': 'Feminino',
    'verification.country': 'País',
    'verification.city': 'Cidade',
    'verification.address': 'Endereço',
    'verification.phone_number': 'Número de Telefone',
    'verification.email': 'Email',
    'verification.update_data': 'Atualizar Dados',
    'verification.data_updated_successfully': 'Dados atualizados com sucesso',
    'verification.error_updating_data': 'Erro ao atualizar dados',
    
    // ProfileSidebar component
    'sidebar.my_profile': 'Meu Perfil',
    'sidebar.recharge': 'Recarregar',
    'sidebar.withdraw': 'Sacar',
    'sidebar.transaction_history': 'Histórico de Transações',
    'sidebar.bonuses': 'Bônus',
    'sidebar.verification': 'Verificação',
    'sidebar.balance': 'Saldo:',
    'sidebar.user_id': 'ID do Usuário:',
    'sidebar.quick_recharge': 'Recarga Rápida',
    
    // Loading page
    'loading.welcome_message': 'Bem-vindo ao cassino mais emocionante!',
    'loading.loading_text': 'Carregando sua experiência de jogo...',
    
    // Game mode dialog
    'game_mode.select_mode': 'Selecione o modo de jogo',
    'game_mode.demo_mode': 'Modo Demo',
    'game_mode.demo_description': 'Jogue grátis sem risco de dinheiro real',
    'game_mode.real_mode': 'Modo Real',
    'game_mode.real_description': 'Jogue com dinheiro real e ganhe prêmios',
    'game_mode.free': 'Grátis',
    'game_mode.real_money': 'Dinheiro Real',
    'game_mode.cancel': 'Cancelar',
    'game_mode.please_select_mode': 'Por favor selecione um modo de jogo',
    
    // Navigation
    'nav.home': 'Início',
    'nav.aviator': 'Aviator',
    'nav.games': 'Jogos',
    'nav.casino': 'Cassino',
    'nav.bonuses': 'Bônus',
    'nav.live_games': 'Jogos <br> ao Vivo',
    
    // Footer
    'footer.general_terms': 'Termos e Condições Gerais',
    'footer.responsible_gaming': 'Jogo Responsável',
    'footer.contact': 'Contato',
    'footer.affiliate_program': 'Programa de Afiliados',
    'footer.privacy_policy': 'Política de Privacidade',
    'footer.about_us': 'Sobre Nós',
    'footer.account_payments': 'Conta, Pagamentos e Bônus',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.close': 'Fechar',
    'common.submit': 'Enviar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    
    // Pages
    'page.deposit': 'Depósito',
    'page.withdrawal': 'Saque',
    'page.profile': 'Meu Perfil',
    'page.verification': 'Verificação',
    'page.detalization': 'Detalização',
    'page.games': 'Jogos',
    'page.casino': 'Cassino',
    'page.bonuses': 'Bônus',
    'page.policies': 'Políticas',
    
    // Home page
    'home.casino': 'Cassino',
    'home.live_games': 'Jogos ao Vivo',
    'home.all_games': 'Todos os Jogos',
    'home.crash': 'Crash',
    'home.valor_games': 'Valor Games',
    'home.all_games_filter': 'Todos os Jogos',
    
    // Footer
    'footer.company_info': 'As informações no site são fornecidas pelo operador do site - a empresa ValorBet N.V., registrada no endereço: Palm Avenue 10, Rosebank, Sint Maarten. A atividade da empresa ValorBet N.V. é licenciada e regulamentada pela IslandGames N.V. (número da licença: No. 1234/JAZ2021-567; válida até 31 de dezembro de 2025) e pela legislação de Sint Maarten. Os pagamentos são processados pela Global Invest Solutions Ltd (número de registro: HE 654321, endereço: Ocean Drive 22, Mesa Verde, 5678, Limassol, Chipre), uma subsidiária da ValorBet N.V.',
    'footer.copyright': '© 2021 - 2025. ValorCasino. Todos os Direitos Reservados',
    'footer.legal_info': 'Informações Legais',
    
    // Policies page
    'policies.user_agreement': 'Acordo do Usuário',
    'policies.responsible_gambling': 'Jogo Responsável',
    'policies.responsible_gaming': 'Jogo Responsável',
    'policies.general_terms': 'Termos e Condições Gerais',
    'policies.risk_disclosure': 'Divulgação de Riscos',
    'policies.deposits_withdrawals': 'Depósitos e Saques',
    'policies.cancellation_policy': 'Política de Cancelamento',
    'policies.refund_policy': 'Política de Reembolso',
    'policies.privacy_policy': 'Política de Privacidade',
    'policies.about_us': 'Sobre Nós',
    'policies.contact': 'Contato',
    'policies.fairness': 'Métodos de Prova de Imparcialidade e RNG',
    'policies.account_payments': 'Conta, Pagamentos e Bônus',
    'policies.aml': 'Políticas AML',
    'policies.self_exclusion': 'Autoexclusão',
    'policies.kyc': 'Política KYC',
    'policies.dispute_resolution': 'Resolução de Disputas',
  },
  ar: {
    // Header
    'header.balance': 'الرصيد:',
    'header.deposit': 'إيداع بنقرة واحدة',
    'header.login': 'تسجيل الدخول',
    'header.register': 'التسجيل',
    'header.games': 'الألعاب',
    'header.casino': 'الكازينو',
    'header.bonuses': 'المكافآت',
    'header.live_games': 'الألعاب المباشرة',
    'header.more': 'المزيد',
    'header.account': 'الحساب',
    'header.menu': 'القائمة',
    
    // Profile page
    'profile.my_profile': 'ملفي الشخصي',
    'profile.personal_data': 'البيانات الشخصية',
    'profile.security': 'الأمان',
    'profile.email_not_verified': 'لم يتم التحقق من بريدك الإلكتروني. يرجى التحقق من بريدك الإلكتروني ولا تنس التحقق من مجلد الرسائل غير المرغوب فيها.',
    'profile.resend_email': 'إعادة إرسال البريد الإلكتروني',
    'profile.first_name': 'الاسم الأول',
    'profile.last_name': 'اسم العائلة',
    'profile.birthday': 'تاريخ الميلاد',
    'profile.gender': 'الجنس',
    'profile.country': 'البلد',
    'profile.city': 'المدينة',
    'profile.address': 'العنوان',
    'profile.phone_number': 'رقم الهاتف',
    'profile.email': 'البريد الإلكتروني',
    'profile.male': 'ذكر',
    'profile.female': 'أنثى',
    'profile.save': 'حفظ',
    'profile.security_settings': 'إعدادات الأمان',
    'profile.old_password': 'كلمة المرور القديمة',
    'profile.new_password': 'كلمة المرور الجديدة',
    'profile.confirm_password': 'تأكيد كلمة المرور',
    'profile.send': 'إرسال',
    'profile.profile_updated': 'تم تحديث الملف الشخصي بنجاح',
    
    // Deposit page
    'deposit.choose_bonus': 'اختر مكافأتك!',
    'deposit.choose_amount': 'اختر مبلغك!',
    'deposit.recharge': 'إعادة شحن',
    'deposit.bonus_percentage': 'مكافأة +{percentage}%',
    'deposit.amount': 'مبلغ الإيداع',
    'deposit.enter_amount': 'أدخل مبلغك (مثال: 100000)',
    'deposit.minimum_amount': 'الحد الأدنى:',
    'deposit.first_name': 'الاسم الأول',
    'deposit.last_name': 'اسم العائلة',
    'deposit.address': 'العنوان',
    'deposit.state': 'الولاية',
    'deposit.city': 'المدينة',
    'deposit.zip': 'الرمز البريدي',
    'deposit.birth_date': 'تاريخ الميلاد',
    'deposit.phone_no': 'رقم الهاتف',
    'deposit.tax_id': 'رقم الهوية الضريبية',
    'deposit.phone_error': 'يجب أن يحتوي رقم الهاتف على 10 أرقام بالضبط',
    'deposit.pagos_success': 'تم معالجة الدفع بنجاح. ستفتح صفحة الدفع.',
    'deposit.pagos_error': 'خطأ في معالجة الدفع. يرجى المحاولة مرة أخرى.',
    'deposit.terms_acceptance': 'بالنقر على إيداع، فإنك تقبل',
    'deposit.terms_conditions': 'الشروط والأحكام',
    'deposit.privacy_policy': 'سياسة الخصوصية',
    'deposit.deposit_button': 'إيداع',
    'deposit.minimum_required': '⚠️ المبلغ الأدنى مطلوب',
    'deposit.minimum_message': 'الحد الأدنى للإيداع هو 60,000 {currency}. يرجى إدخال مبلغ أكبر من أو يساوي هذه القيمة.',
    'deposit.understood': 'مفهوم',
    'deposit.safety_pay': 'SafetyPay Express 4.0',
    
    // Additional deposit texts
    'deposit.page_title': 'إعادة شحن',
    'deposit.choose_method': 'اختر طريقة الإيداع',
    
    // Detalization page
    'detalization.deposits': 'الإيداعات',
    'detalization.payments': 'المدفوعات',
    'detalization.date_time': 'التاريخ والوقت',
    'detalization.transaction': 'المعاملة',
    'detalization.amount': 'المبلغ',
    'detalization.payment_method': 'طريقة الدفع',
    'detalization.status': 'الحالة',
    'detalization.empty_deposits': 'تاريخ المعاملات فارغ',
    'detalization.empty_payments': 'لا توجد طلبات سحب بعد',
    'detalization.deposits_description': 'أعد شحن حسابك، ضع الرهانات واحصل على الأرباح!',
    'detalization.payments_description': 'طلبات السحب ستظهر هنا',
    'detalization.recharge_button': 'إعادة شحن',
    'detalization.withdraw_button': 'الحصول على ربح',
    'detalization.status_completed': 'مكتمل',
    'detalization.status_approved': 'موافق عليه',
    'detalization.status_waiting': 'في الانتظار',
    'detalization.status_pending': 'معلق',
    
    // Withdrawal page
    'withdrawal.page_title': 'سحب الأموال',
    'withdrawal.choose_method': 'اختر طريقة السحب',
    'withdrawal.bank_transfer': 'تحويل بنكي',
    'withdrawal.details': 'تفاصيل السحب',
    'withdrawal.ready_to_withdraw': 'جاهز لسحب النقود',
    'withdrawal.amount_label': 'المبلغ (الحد الأقصى: {balance} {currency})',
    'withdrawal.minimum_amount': 'الحد الأدنى ',
    'withdrawal.client_phone': 'هاتف العميل',
    'withdrawal.account_type': 'حساب جاري أو توفير',
    'withdrawal.account_type_placeholder': 'جاري أو توفير',
    'withdrawal.account_number': 'رقم الحساب',
    'withdrawal.document_type': 'نوع الوثيقة',
    'withdrawal.document_type_placeholder': 'هوية، جواز سفر، إلخ',
    'withdrawal.document_number': 'رقم الوثيقة',
    'withdrawal.bank': 'البنك',
    'withdrawal.select_bank': 'اختر بنكك',
    'withdrawal.bancolombia': 'بانكولومبيا',
    'withdrawal.davivienda': 'دافيفيندا',
    'withdrawal.bbva': 'BBVA',
    'withdrawal.banco_bogota': 'بنك بوغوتا',
    'withdrawal.banco_agrario': 'البنك الزراعي',
    'withdrawal.banco_popular': 'البنك الشعبي',
    'withdrawal.banco_occidente': 'بنك أوكسيدنتي',
    'withdrawal.banco_caja_social': 'بنك كاخا سوسيال',
    'withdrawal.request_withdrawal': 'طلب سحب',
    
    // Bonuses page
    'bonuses.hero_title': 'أكثر كازينو أونلاين سخاءً!',
    'bonuses.all_bonuses': 'جميع المكافآت',
    'bonuses.my_active_bonuses': 'مكافآتي النشطة',
    'bonuses.available_for_me': 'متاح لي',
    'bonuses.archive': 'الأرشيف',
    'bonuses.promo_title': 'حتى +400% على إيداعك مع كود ترويجي!',
    'bonuses.promo_description': 'كل كود ترويجي فريد ويمنح من +50% إلى +1000% لرصيد المكافآت الخاص بك.',
    'bonuses.confirm': 'تأكيد',
    'bonuses.activation_error': 'خطأ في التفعيل',
    'bonuses.promo_not_found': 'لم يتم العثور على الكود الترويجي.',
    'bonuses.ok': 'موافق',
    'bonuses.promo_placeholder': 'أدخل الكود الترويجي الخاص بك',
    
    // All Games page
    'all_games.top_games': 'أفضل الألعاب',
    'all_games.popular': 'شائع',
    'all_games.hot': 'ساخن',
    'all_games.search_placeholder': 'بحث...',
    'all_games.providers': 'المزودون',
    'all_games.categories': 'الفئات',
    'all_games.clear': 'مسح',
    'all_games.all_games': 'جميع الألعاب',
    'all_games.all_games_mobile': 'جميع الألعاب',
    'all_games.game': 'لعبة',
    'all_games.games': 'ألعاب',
    
    // Verification page
    'verification.personal_data': 'البيانات الشخصية',
    'verification.first_name': 'الاسم الأول',
    'verification.last_name': 'اسم العائلة',
    'verification.birthday': 'تاريخ الميلاد',
    'verification.gender': 'الجنس',
    'verification.male': 'ذكر',
    'verification.female': 'أنثى',
    'verification.country': 'البلد',
    'verification.city': 'المدينة',
    'verification.address': 'العنوان',
    'verification.phone_number': 'رقم الهاتف',
    'verification.email': 'البريد الإلكتروني',
    'verification.update_data': 'تحديث البيانات',
    'verification.data_updated_successfully': 'تم تحديث البيانات بنجاح',
    'verification.error_updating_data': 'خطأ في تحديث البيانات',
    
    // ProfileSidebar component
    'sidebar.my_profile': 'ملفي الشخصي',
    'sidebar.recharge': 'إعادة الشحن',
    'sidebar.withdraw': 'سحب',
    'sidebar.transaction_history': 'تاريخ المعاملات',
    'sidebar.bonuses': 'المكافآت',
    'sidebar.verification': 'التحقق',
    'sidebar.balance': 'الرصيد:',
    'sidebar.user_id': 'معرف المستخدم:',
    'sidebar.quick_recharge': 'شحن سريع',
    
    // Loading page
    'loading.welcome_message': 'مرحباً بك في أكثر كازينو إثارة!',
    'loading.loading_text': 'جاري تحميل تجربة اللعب الخاصة بك...',
    
    // Game mode dialog
    'game_mode.select_mode': 'اختر وضع اللعب',
    'game_mode.demo_mode': 'وضع التجربة',
    'game_mode.demo_description': 'العب مجاناً بدون مخاطر مالية حقيقية',
    'game_mode.real_mode': 'الوضع الحقيقي',
    'game_mode.real_description': 'العب بأموال حقيقية واكسب الجوائز',
    'game_mode.free': 'مجاني',
    'game_mode.real_money': 'أموال حقيقية',
    'game_mode.cancel': 'إلغاء',
    'game_mode.please_select_mode': 'يرجى اختيار وضع اللعب',
    
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.aviator': 'أفييتور',
    'nav.games': 'الألعاب',
    'nav.casino': 'الكازينو',
    'nav.bonuses': 'المكافآت',
    'nav.live_games': 'الألعاب المباشرة',
    
    // Footer
    'footer.general_terms': 'الشروط والأحكام العامة',
    'footer.responsible_gaming': 'اللعب المسؤول',
    'footer.contact': 'اتصل بنا',
    'footer.affiliate_program': 'برنامج الشراكة',
    'footer.privacy_policy': 'سياسة الخصوصية',
    'footer.about_us': 'معلومات عنا',
    'footer.account_payments': 'الحساب والمدفوعات والمكافآت',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.continue': 'متابعة',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    
    // Pages
    'page.deposit': 'إيداع',
    'page.withdrawal': 'سحب',
    'page.profile': 'ملفي الشخصي',
    'page.verification': 'التحقق',
    'page.detalization': 'التفاصيل',
    'page.games': 'الألعاب',
    'page.casino': 'الكازينو',
    'page.bonuses': 'المكافآت',
    'page.policies': 'السياسات',
    
    // Home page
    'home.casino': 'الكازينو',
    'home.live_games': 'الألعاب المباشرة',
    'home.all_games': 'جميع الألعاب',
    'home.crash': 'كراش',
    'home.valor_games': 'فالور جيمز',
    'home.all_games_filter': 'جميع الألعاب',
    
    // Footer
    'footer.company_info': 'المعلومات على الموقع مقدمة من قبل مشغل الموقع - شركة ValorBet N.V.، المسجلة في العنوان: Palm Avenue 10، Rosebank، Sint Maarten. نشاط شركة ValorBet N.V. مرخص ومنظم من قبل IslandGames N.V. (رقم الترخيص: No. 1234/JAZ2021-567؛ صالح حتى 31 ديسمبر 2025) ومن قبل تشريعات Sint Maarten. المدفوعات تتم معالجتها من قبل Global Invest Solutions Ltd (رقم التسجيل: HE 654321، العنوان: Ocean Drive 22، Mesa Verde، 5678، Limassol، قبرص)، شركة تابعة لـ ValorBet N.V.',
    'footer.copyright': '© 2021 - 2025. ValorCasino. جميع الحقوق محفوظة',
    'footer.legal_info': 'المعلومات القانونية',
    
    // Policies page
    'policies.user_agreement': 'اتفاقية المستخدم',
    'policies.responsible_gambling': 'المقامرة المسؤولة',
    'policies.responsible_gaming': 'اللعب المسؤول',
    'policies.general_terms': 'الشروط والأحكام العامة',
    'policies.risk_disclosure': 'الإفصاح عن المخاطر',
    'policies.deposits_withdrawals': 'الإيداعات والسحوبات',
    'policies.cancellation_policy': 'سياسة الإلغاء',
    'policies.refund_policy': 'سياسة الاسترداد',
    'policies.privacy_policy': 'سياسة الخصوصية',
    'policies.about_us': 'معلومات عنا',
    'policies.contact': 'اتصل بنا',
    'policies.fairness': 'طرق إثبات النزاهة و RNG',
    'policies.account_payments': 'الحساب والمدفوعات والمكافآت',
    'policies.aml': 'سياسات مكافحة غسل الأموال',
    'policies.self_exclusion': 'الاستبعاد الذاتي',
    'policies.kyc': 'سياسة اعرف عميلك',
    'policies.dispute_resolution': 'حل النزاعات',
  },
  fr: {
    // Header
    'header.balance': 'Solde:',
    'header.deposit': 'Dépôt en 1 clic',
    'header.login': 'Connexion',
    'header.register': 'S\'inscrire',
    'header.games': 'Jeux',
    'header.casino': 'Casino',
    'header.bonuses': 'Bonus',
    'header.live_games': 'Jeux en Direct',
    'header.more': 'Plus',
    'header.account': 'Compte',
    'header.menu': 'Menu',
    
    // Profile page
    'profile.my_profile': 'Mon Profil',
    'profile.personal_data': 'Données Personnelles',
    'profile.security': 'Sécurité',
    'profile.email_not_verified': 'Votre email n\'a pas été vérifié. Veuillez vérifier votre email et n\'oubliez pas de vérifier votre dossier spam.',
    'profile.resend_email': 'Renvoyer l\'Email',
    'profile.first_name': 'Prénom',
    'profile.last_name': 'Nom de Famille',
    'profile.birthday': 'Anniversaire',
    'profile.gender': 'Sexe',
    'profile.country': 'Pays',
    'profile.city': 'Ville',
    'profile.address': 'Adresse',
    'profile.phone_number': 'Numéro de Téléphone',
    'profile.email': 'Email',
    'profile.male': 'Masculin',
    'profile.female': 'Féminin',
    'profile.save': 'Enregistrer',
    'profile.security_settings': 'Paramètres de Sécurité',
    'profile.old_password': 'Ancien Mot de Passe',
    'profile.new_password': 'Nouveau Mot de Passe',
    'profile.confirm_password': 'Confirmer le Mot de Passe',
    'profile.send': 'Envoyer',
    'profile.profile_updated': 'Profil mis à jour avec succès',
    
    // Deposit page
    'deposit.choose_bonus': 'Choisissez votre bonus!',
    'deposit.choose_amount': 'Choisissez votre montant!',
    'deposit.recharge': 'Recharger',
    'deposit.bonus_percentage': 'Bonus +{percentage}%',
    'deposit.amount': 'Montant du dépôt',
    'deposit.enter_amount': 'Entrez votre montant (ex: 100000)',
    'deposit.minimum_amount': 'Montant minimum:',
    'deposit.first_name': 'Prénom',
    'deposit.last_name': 'Nom de famille',
    'deposit.address': 'Adresse',
    'deposit.state': 'État/Province',
    'deposit.city': 'Ville',
    'deposit.zip': 'Code postal',
    'deposit.birth_date': 'Date de naissance',
    'deposit.phone_no': 'Numéro de téléphone',
    'deposit.tax_id': 'Numéro d\'identification fiscale',
    'deposit.phone_error': 'Le numéro de téléphone doit contenir exactement 10 chiffres',
    'deposit.pagos_success': 'Paiement traité avec succès. La page de paiement va s\'ouvrir.',
    'deposit.pagos_error': 'Erreur lors du traitement du paiement. Veuillez réessayer.',
    'deposit.terms_acceptance': 'En cliquant sur Dépôt, vous acceptez les',
    'deposit.terms_conditions': 'Termes et conditions',
    'deposit.privacy_policy': 'Politique de confidentialité',
    'deposit.deposit_button': 'Déposer',
    'deposit.minimum_required': '⚠️ Montant minimum requis',
    'deposit.minimum_message': 'Le montant minimum de dépôt est de 60,000 {currency}. Veuillez entrer un montant supérieur ou égal à cette valeur.',
    'deposit.understood': 'Compris',
    'deposit.safety_pay': 'SafetyPay Express 4.0',
    
    // Additional deposit texts
    'deposit.page_title': 'Recharger',
    'deposit.choose_method': 'Choisissez la méthode de dépôt',
    
    // Detalization page
    'detalization.deposits': 'dépôts',
    'detalization.payments': 'paiements',
    'detalization.date_time': 'Date et Heure',
    'detalization.transaction': 'Transaction',
    'detalization.amount': 'Montant',
    'detalization.payment_method': 'Méthode de Paiement',
    'detalization.status': 'Statut',
    'detalization.empty_deposits': 'L\'historique des transactions est vide',
    'detalization.empty_payments': 'Aucune demande de retrait pour le moment',
    'detalization.deposits_description': 'Rechargez votre compte, placez des paris et obtenez des profits!',
    'detalization.payments_description': 'Les demandes de retrait seront affichées ici',
    'detalization.recharge_button': 'Recharger',
    'detalization.withdraw_button': 'Obtenir un profit',
    'detalization.status_completed': 'terminé',
    'detalization.status_approved': 'approuvé',
    'detalization.status_waiting': 'en attente',
    'detalization.status_pending': 'en attente',
    
    // Withdrawal page
    'withdrawal.page_title': 'Retrait de fonds',
    'withdrawal.choose_method': 'Choisissez la méthode de retrait',
    'withdrawal.bank_transfer': 'VIREMENT BANCAIRE',
    'withdrawal.details': 'Détails du retrait',
    'withdrawal.ready_to_withdraw': 'Prêt à retirer de l\'argent',
    'withdrawal.amount_label': 'Montant (Max: {balance} {currency})',
    'withdrawal.minimum_amount': 'Minimum',
    'withdrawal.client_phone': 'Téléphone du client',
    'withdrawal.account_type': 'Compte courant ou épargne',
    'withdrawal.account_type_placeholder': 'courant ou épargne',
    'withdrawal.account_number': 'Numéro de compte',
    'withdrawal.document_type': 'Type de Document',
    'withdrawal.document_type_placeholder': 'carte d\'identité, passeport, etc.',
    'withdrawal.document_number': 'Numéro du Document',
    'withdrawal.bank': 'Banque',
    'withdrawal.select_bank': 'Sélectionnez votre banque',
    'withdrawal.bancolombia': 'Bancolombia',
    'withdrawal.davivienda': 'Davivienda',
    'withdrawal.bbva': 'BBVA',
    'withdrawal.banco_bogota': 'Banco de Bogotá',
    'withdrawal.banco_agrario': 'Banco Agrario',
    'withdrawal.banco_popular': 'Banco Popular',
    'withdrawal.banco_occidente': 'Banco de Occidente',
    'withdrawal.banco_caja_social': 'Banco Caja Social',
    'withdrawal.request_withdrawal': 'Demander un retrait',
    
    // Bonuses page
    'bonuses.hero_title': 'Le casino en ligne le plus généreux !',
    'bonuses.all_bonuses': 'Tous les bonus',
    'bonuses.my_active_bonuses': 'Mes bonus actifs',
    'bonuses.available_for_me': 'Disponible pour moi',
    'bonuses.archive': 'Archives',
    'bonuses.promo_title': 'Jusqu\'à +400% sur votre dépôt avec un code promotionnel !',
    'bonuses.promo_description': 'Chaque code promotionnel est unique et accorde de +50% à +1000% à votre solde de bonus.',
    'bonuses.confirm': 'Confirmer',
    'bonuses.activation_error': 'Erreur d\'activation',
    'bonuses.promo_not_found': 'Code promotionnel non trouvé.',
    'bonuses.ok': 'Ok',
    'bonuses.promo_placeholder': 'Entrez votre code promotionnel',
    
    // All Games page
    'all_games.top_games': 'Top Jeux',
    'all_games.popular': 'Populaire',
    'all_games.hot': 'Chaud',
    'all_games.search_placeholder': 'Rechercher...',
    'all_games.providers': 'Fournisseurs',
    'all_games.categories': 'Catégories',
    'all_games.clear': 'Effacer',
    'all_games.all_games': 'Tous les Jeux',
    'all_games.all_games_mobile': 'Tous les jeux',
    'all_games.game': 'jeu',
    'all_games.games': 'jeux',
    
    // Verification page
    'verification.personal_data': 'Données Personnelles',
    'verification.first_name': 'Prénom',
    'verification.last_name': 'Nom de Famille',
    'verification.birthday': 'Anniversaire',
    'verification.gender': 'Sexe',
    'verification.male': 'Masculin',
    'verification.female': 'Féminin',
    'verification.country': 'Pays',
    'verification.city': 'Ville',
    'verification.address': 'Adresse',
    'verification.phone_number': 'Numéro de Téléphone',
    'verification.email': 'Email',
    'verification.update_data': 'Mettre à Jour les Données',
    'verification.data_updated_successfully': 'Données mises à jour avec succès',
    'verification.error_updating_data': 'Erreur lors de la mise à jour des données',
    
    // ProfileSidebar component
    'sidebar.my_profile': 'Mon Profil',
    'sidebar.recharge': 'Recharger',
    'sidebar.withdraw': 'Retirer',
    'sidebar.transaction_history': 'Historique des Transactions',
    'sidebar.bonuses': 'Bonus',
    'sidebar.verification': 'Vérification',
    'sidebar.balance': 'Solde:',
    'sidebar.user_id': 'ID Utilisateur:',
    'sidebar.quick_recharge': 'Recharge Rapide',
    
    // Loading page
    'loading.welcome_message': 'Bienvenue dans le casino le plus passionnant !',
    'loading.loading_text': 'Chargement de votre expérience de jeu...',
    
    // Game mode dialog
    'game_mode.select_mode': 'Sélectionnez le mode de jeu',
    'game_mode.demo_mode': 'Mode Démo',
    'game_mode.demo_description': 'Jouez gratuitement sans risque d\'argent réel',
    'game_mode.real_mode': 'Mode Réel',
    'game_mode.real_description': 'Jouez avec de l\'argent réel et gagnez des prix',
    'game_mode.free': 'Gratuit',
    'game_mode.real_money': 'Argent Réel',
    'game_mode.cancel': 'Annuler',
    'game_mode.please_select_mode': 'Veuillez sélectionner un mode de jeu',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.aviator': 'Aviator',
    'nav.games': 'Jeux',
    'nav.casino': 'Casino',
    'nav.bonuses': 'Bonus',
    'nav.live_games': 'Jeux <br> en Direct',
    
    // Footer
    'footer.general_terms': 'Conditions Générales',
    'footer.responsible_gaming': 'Jeu Responsable',
    'footer.contact': 'Contact',
    'footer.affiliate_program': 'Programme d\'Affiliation',
    'footer.privacy_policy': 'Politique de Confidentialité',
    'footer.about_us': 'À Propos',
    'footer.account_payments': 'Compte, Paiements et Bonus',
    
    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.continue': 'Continuer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    
    // Pages
    'page.deposit': 'Dépôt',
    'page.withdrawal': 'Retrait',
    'page.profile': 'Mon Profil',
    'page.verification': 'Vérification',
    'page.detalization': 'Détail',
    'page.games': 'Jeux',
    'page.casino': 'Casino',
    'page.bonuses': 'Bonus',
    'page.policies': 'Politiques',
    
    // Home page
    'home.casino': 'Casino',
    'home.live_games': 'Jeux en Direct',
    'home.all_games': 'Tous les Jeux',
    'home.crash': 'Crash',
    'home.valor_games': 'Valor Games',
    'home.all_games_filter': 'Tous les Jeux',
    
    // Footer
    'footer.company_info': 'Les informations sur le site sont fournies par l\'opérateur du site - la société ValorBet N.V., enregistrée à l\'adresse: Palm Avenue 10, Rosebank, Sint Maarten. L\'activité de la société ValorBet N.V. est licenciée et réglementée par IslandGames N.V. (numéro de licence: No. 1234/JAZ2021-567; valide jusqu\'au 31 décembre 2025) et par la législation de Sint Maarten. Les paiements sont traités par Global Invest Solutions Ltd (numéro d\'enregistrement: HE 654321, adresse: Ocean Drive 22, Mesa Verde, 5678, Limassol, Chypre), une filiale de ValorBet N.V.',
    'footer.copyright': '© 2021 - 2025. ValorCasino. Tous Droits Réservés',
    'footer.legal_info': 'Informations Légales',
    
    // Policies page
    'policies.user_agreement': 'Accord d\'Utilisateur',
    'policies.responsible_gambling': 'Jeu Responsable',
    'policies.responsible_gaming': 'Jeu Responsable',
    'policies.general_terms': 'Conditions Générales',
    'policies.risk_disclosure': 'Divulgation des Risques',
    'policies.deposits_withdrawals': 'Dépôts et Retraits',
    'policies.cancellation_policy': 'Politique d\'Annulation',
    'policies.refund_policy': 'Politique de Remboursement',
    'policies.privacy_policy': 'Politique de Confidentialité',
    'policies.about_us': 'À Propos de Nous',
    'policies.contact': 'Contact',
    'policies.fairness': 'Méthodes de Preuve d\'Équité et RNG',
    'policies.account_payments': 'Compte, Paiements et Bonus',
    'policies.aml': 'Politiques Anti-Blanchiment',
    'policies.self_exclusion': 'Auto-Exclusion',
    'policies.kyc': 'Politique KYC',
    'policies.dispute_resolution': 'Résolution des Litiges',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && ['es', 'en', 'pt', 'ar', 'fr'].includes(savedLanguage)) {
        setLanguage(savedLanguage);
      }
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
